// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSy***********************************', // Replace with your actual API key
    appId: '1:758751119890:web:860cf7e8261cf53ce1e6cb',
    messagingSenderId: '758751119890',
    projectId: 'mexc-alwaly-bot-42320068',
    authDomain: 'mexc-alwaly-bot-42320068.firebaseapp.com',
    storageBucket: 'mexc-alwaly-bot-42320068.appspot.com',
    measurementId: 'G-XXXXXXXXXX', // Replace with your actual measurement ID
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSy***********************************', // Replace with your actual API key
    appId: '1:758751119890:android:c0a1b2c3d4e5f6a7b8c9d0', // Example, replace with your actual android app id
    messagingSenderId: '758751119890',
    projectId: 'mexc-alwaly-bot-42320068',
    storageBucket: 'mexc-alwaly-bot-42320068.appspot.com',
  );
}
